### PR TITLE
Bliss2

### PR DESCRIPTION
**Pull request by LinguList**
Here's the latest addons with forms etc. created with Glottolog 4.7 and Concepticon 3.1

### CODE REVIEW

**Comment by johenglisch** [comment]
I just fixed a minor nitpick because that if statement in `_add_languages` behaves weirdly if `language.name` has a `None` value:

    >>> language_name = None
    >>> str(language_name).strip()
    'None'
    >>> not str(language_name).strip() or language_name == 'None'
    False

Again, it's a nitpick -- we don't seem to have any `None` values in our data right now.  But it seems a bit more robust.

Other than that this looks good to go.

**Comment by LinguList** [comment]
And if it is easy for you to add that right away, @johenglisch, please do so :)

**Comment by johenglisch** [comment]
>please do so

I already did (I hope that wasn't too hasty).

>if we agree it is save to replace the line without running again

I had it run in the background this morning just to make sure and the line change didn't affect anything.

**Comment by LinguList** [comment]
Super, if you are all fine, we can merge then and also release this as version 1.0 of lexibank :)

**Comment by LinguList** [comment]
The servamalagasy key is not found, because the glottocode was modified, and needs to be updated, so it either works with glottolog 4.4, but I thought we better use 4.7. So the tests must be adjusted here.

We have problems of a few duplicates, but in individual datasets. I suggest we leave all cases related to new data releases out for now, using explicitly the 0.2 data but with the new code that more transparently shares forms for some major candidates (which have transcriptions and the like).

**Comment by johenglisch** [comment]
>The servamalagasy key is not found, because the glottocode was modified, and
>needs to be updated, so it either works with glottolog 4.4, but I thought we
>better use 4.7.

Hm, somehow that feels off to me.  The language is loaded successfully and added to `frequencies.csv` (and I assume counting sounds also requires access to the actual forms?):

    $ csvgrep -c Language_ID -m servamalagasy-MerinaMaevatanana cldf/frequencies.csv \
        | csvcut -c Parameter_ID,Value \
        | head
    Parameter_ID,Value
    from_unrounded_close_front_to_rounded_close_back_diphthong,1
    from_unrounded_close_front_to_unrounded_close-mid_front_diphthong,1
    from_unrounded_close_front_to_unrounded_open_front_diphthong,9
    from_unrounded_open_front_to_non-syllabic_rounded_close_back_diphthong,7
    from_unrounded_open_front_to_non-syllabic_unrounded_close_front_diphthong,8
    pre-nasalized_voiced_alveolar_sibilant_affricate_consonant,3
    pre-nasalized_voiced_alveolar_stop_consonant,5
    pre-nasalized_voiced_bilabial_stop_consonant,4
    pre-nasalized_voiced_retroflex_sibilant_affricate_consonant,9

But at the same time its missing from the form table and the language table:

    $ unzip -q -c cldf/forms.csv.zip \
        | csvgrep -c Language_ID -m servamalagasy-MerinaMaevatanana \
        | csvcut -c Parameter_ID,Value
    Parameter_ID,Value

Intuitively that feels more like a bug in the program rather than a Glottolog version thing.  No matter what version of glottolog we're using, I would expect the language ID to appear either in all relevant tables or in none of them (whichever is desired for a specific case).

>So the tests must be adjusted here.

I don't quite know what you mean by ‘adjusting the tests’.  The tests are just `cldf validate`.

>I suggest we leave all cases related to new data releases out for now, using
>explicitly the 0.2 data but with the new code that more transparently shares
>forms for some major candidates.

Do you mean load the data specified in the old `lexibank.tsv` file rather than the data from the newer `lexibank-bliss.tsv`?  Shouldn't be a problem but I wonder if we're tossing out the baby with the bath water there.

**Comment by LinguList** [comment]
Yes, that's weird and not very pleasant, that we have this problem now. So there is a bug that must be fixed before releasing it. But my intuition that this is related to the glottocode was right, becase the glottocode is `meri1243`, which is outdated. The code I wrote tries to exclude these languages from being written to the language table (and to the form table). It is possible, however, that the check was not applied to writing frequencies (!). So it must be applied to all cases.

**Comment by LinguList** [comment]
By adjusting the test: it was an error from my side, I did not know we just cldf validate here.

**Comment by LinguList** [comment]
@johenglisch, I found the bug!

in the *py script, we have the lines 385-387 in the function `_add_languages`

```
                if language.latitude and language.glottocode and condition(language):
                    _add_language(writer, language, features, attr_features,
                            collection=collection, visited=visited)
                    yield language
```

The problem is that I introduced a stop to `_add_language`, if the glottocode is NOT in glottolog (the `languoids` dictionary). In this case, it looks for a `KeyError` and returns `None`. However, as we don't check for the return value of `_add_language`, it goes on to `yield` the language object, so frequency is calculated for the invalid glottocode language anyway. 

I think, a fix would consist in just rewriting as:

```
                if language.latitude and language.glottocode and condition(language):
                    if _add_language(writer, language, features, attr_features,
                            collection=collection, visited=visited):
                        yield language
```

**Comment by LinguList** [comment]
I can try and rerun this on Monday, if nobody else has time for it. On Tuesday / Wednesday I am not in Leipzig, where I have my fast computer, but would then be back on Thursday.

**Comment by LinguList** [comment]
I am trying to run it now with the proposed modification.

**Comment by LinguList** [comment]
Update: I just pushed the new version in which the tests run, but there's a warning that the column Dataset is not specified in the file languages.csv. If any of you has a quick fix for that (as I don't have time to look further in it today), this would be super, as it would mean we can merge already.

**Comment by LinguList** [comment]
The modification, btw. required to make a check with True and False, since the function always returned None, and now it is explicit in telling if it failed or if it worked.

**Comment by johenglisch** [comment]
>column Dataset is not specified

I'll take a look at that -- theoretically this should only involve adding one line to the schema.

**Comment by LinguList** [comment]
Update 2: now, the tests run without an error on my computer. So I think this could then be merged, to publish version 1.0 of lexibank data.

**Comment by johenglisch** [comment]
>I think this could then be merged

Sounds good to me.

>publish version 1.0 of lexibank data

Who should do the release?  Do you want me to do it or do you want to have the honour of pressing the button yourself? (^^)

**Pull request merged**
