### PR TITLE
Use `cldfzenodo` to download data

### PR DESCRIPTION
**Pull request by johenglisch**
Note: `cldfzenodo` seems to only download the cldf data itself, not the entire bench.
`cldfbench cldfmake` seems to work just fine, but I don't know if this could break any other commands.

### CODE REVIEW

**Comment by LinguList** [comment]
It would be good to decide ideally early next week if we make this PR a part of the new version or now. I'd opt for releasing the current version as version 0.1 first (I added the .zenodo.json already), and later take this as an updated version.

**Comment by xrotwang** [comment]
Sounds like a good plan

**Comment by LinguList** [comment]
I don't find the repo on zenodo, although it is online. Do we have to wait here now?

**Comment by xrotwang** [comment]
? which repos?

**Comment by LinguList** [comment]
lexibank-analysed

**Comment by LinguList** [comment]
I wanted to make the 0.1 release after having made this one public.

**Comment by xrotwang** [comment]
ah, ok. will wire it up.

**Comment by LinguList** [comment]
If you can make the release, would be perfect. I'd then insert the link in teh paper and finalize the paper on Monday (figures are already done, but not yet inserted, references as well).

**Comment by xrotwang** [comment]
https://github.com/lexibank/lexibank-analysed/releases/tag/v0.2

v0.2 - because v0.1 had invalid .zenodo.json :)

**Comment by LinguList** [comment]
Sorry, I was so sure that this .zenodo.json was right this time :(

**Comment by LinguList** [comment]
We should merge this PR now, so we can proceed!

**Comment by FredericBlum** [comment]
@LinguList This was never merged, and now there seem to be some conflicts. If we still want to update this, I could write the changes here into a more recent version of the cldfbench script.

**Review by LinguList — APPROVED** [review]

**Comment by chrzyki** [comment]
Conflict resolved in https://github.com/lexibank/lexibank-analysed/pull/33/commits/405c40022576b65075321031a812a4fddfbe25f4.

**Comment by LinguList** [comment]
Danke!!!

**Pull request merged**
